In [1]:
# 加载模块
import torch

In [2]:
# 加载PyTorch模块中提供的损失函数实现类
from torch.nn import MSELoss

In [3]:
# 数据集中的各个样本对应的模型预测-输出标记 => 一维张量
y_hat = torch.randn(size=(50, ), dtype=torch.float32)  # 在计算机内存中一次性存储多个数, 并且这些数是服从标准正态分布的随机数
y = torch.randn(size=(50, ), dtype=torch.float32)

In [4]:
# 1.选择衡量模型预测-输出标记和真实-标签之间差异的 某种形式的误差
criterion = MSELoss()
# 2.代入数据集中的预测-输出标记和真实-标签 计算 具体的误差数值
loss = criterion(y_hat, y)

In [5]:
loss

tensor(2.5532)

##### 实例化MSELoss类的对象的时候可以传入的一个参数reduction

In [6]:
# reduction的值设置为"mean"(默认值), 计算MSE
criterion = MSELoss(reduction="mean")
loss = criterion(y_hat, y)

In [7]:
loss

tensor(2.5532)

In [8]:
# reduction的值设置为"sum", 计算SSE
criterion = MSELoss(reduction="sum")
loss = criterion(y_hat, y)

In [9]:
loss

tensor(127.6603)

In [10]:
# 加载模块
import torch
import time

In [11]:
# 加载真实数据集, 合成虚拟数据集(synthesis)
# 设置随机种子
torch.random.manual_seed(55)

# 1.定义数据集中样本个数
m = 3 * pow(10, 3)
# 2.定义数据集中每一个样本的特征变量个数
n = 4
# 3.生成训练数据集
X = torch.rand(size=(m, n), dtype=torch.float32)
y = torch.randint(low=0, high=2, size=(m, 1), dtype=torch.float32)
# 4.生成模型的权重
w = torch.rand(size=(n, 1), dtype=torch.float32, requires_grad=True)

In [12]:
pow(10, 3)

1000

##### 使用神经网络模型实现逻辑回归

In [13]:
# 1.整合信息
z_hat = torch.mm(X, w)
# 2.加工信息
sigma = torch.sigmoid(z_hat)

In [14]:
sigma

tensor([[0.8551],
        [0.7369],
        [0.6295],
        ...,
        [0.6459],
        [0.7975],
        [0.7884]], grad_fn=<SigmoidBackward0>)

In [15]:
# 查看张量的维度
y.ndim

2

In [16]:
# 查看张量的形状
y.shape

torch.Size([3000, 1])

In [17]:
# 查看张量的维度
sigma.ndim

2

In [18]:
# 查看张量的形状
sigma.shape

torch.Size([3000, 1])

In [19]:
torch.log(sigma)

tensor([[-0.1566],
        [-0.3054],
        [-0.4628],
        ...,
        [-0.4371],
        [-0.2263],
        [-0.2377]], grad_fn=<LogBackward0>)

In [20]:
torch.log(1 - sigma)

tensor([[-1.9314],
        [-1.3351],
        [-0.9929],
        ...,
        [-1.0382],
        [-1.5970],
        [-1.5531]], grad_fn=<LogBackward0>)

In [21]:
# 计算代价函数的具体函数值
cost = -(1 / m) * torch.sum(y * torch.log(sigma) + (1-y) * torch.log((1-sigma)))

In [22]:
cost

tensor(0.8601, grad_fn=<MulBackward0>)

In [23]:
# 加载模块
import torch
import time
# 设置随机数种子
torch.random.manual_seed(55)

# 加载数据集
# 1.数据集中样本的个数m
m = 3 * pow(10, 6)
# 2.数据集中每一个样本的特征变量数n
n = 4
# 3.合成训练数据集X => 特征张量
X = torch.randn(size=(m, n), dtype=torch.float32)
# 3.合成真实标签y => 特征张量
y = torch.randint(low=0, high=2, size=(m, 1), dtype=torch.float32)

# 4.合成模型的权重
w = torch.randn(size=(n, 1), requires_grad=True, dtype=torch.float32)

In [24]:
# 整合信息
z_hat = torch.mm(X, w)
# 加工信息
sigma = torch.sigmoid(z_hat)

In [25]:
start = time.time()
# 计算代价函数的具体函数值
cost = -(1 / m) * torch.sum(y * torch.log(sigma) + (1-y) * torch.log((1-sigma)))
end = time.time()
print(f"该段代码耗时: {end-start}s")

该段代码耗时: 0.0363767147064209s


In [36]:
start = time.time()
# 计算代价函数的具体函数值
cost = -(1 / m) * sum(y * torch.log(sigma) + (1-y) * torch.log((1-sigma)))
end = time.time()
print(f"该段代码耗时: {end-start}s")

该段代码耗时: 17.519542932510376s


In [26]:
# 加载模块
import torch
from torch.nn import BCELoss, BCEWithLogitsLoss

# BCELoss在计算代价函数的函数值的时候, 传入的是加工信息的结果和真实标签
criterion = BCELoss()
loss = criterion(sigma, y)
print(f"损失函数的值为: {loss}")

# BCEWithLogitsLoss在计算代价函数的函数值的时候, 传入的是整合信息的结果和真实标签
criterion = BCEWithLogitsLoss()
loss = criterion(z_hat, y)
print(f"损失函数的值为: {loss}")

损失函数的值为: 1.1397103071212769
损失函数的值为: 1.1397103071212769


In [27]:
criterion2 = BCELoss()
loss2 = criterion2(sigma, y)
print(f"损失函数的值为: {loss2}")

criterion2 = BCEWithLogitsLoss()
loss2 = criterion2(z_hat, y)
print(f"损失函数的值为: {loss2}")

损失函数的值为: 1.1397103071212769
损失函数的值为: 1.1397103071212769


In [28]:
# 加载模块
from torch.nn import functional as F

loss3 = F.binary_cross_entropy(sigma, y)
print(f"损失函数的值为: {loss3}")

loss3 = F.binary_cross_entropy_with_logits(z_hat, y)
print(f"损失函数的值为: {loss3}")

损失函数的值为: 1.1397103071212769
损失函数的值为: 1.1397103071212769


##### 多分类任务的交叉熵损失函数

In [36]:
# 加载模块
import torch
from torch.nn import LogSoftmax, NLLLoss, CrossEntropyLoss

# 设置随机数种子
torch.random.manual_seed(55)

# 加载数据
# 1.数据集中样本的个数. e.g. m=300
m = 3 * pow(10, 2)
# 2.数据集中特征变量的个数. e.g. n=4
n = 4
# 3.数据集中多分类的不同类别数. e.g. c=3
c = 3

# 合成数据集
X = torch.randn(size=(m, n), dtype=torch.float32)
y = torch.randint(low=0, high=c, size=(m, ), dtype=torch.float32)

# 训练模型, 拟合数据集 => 得到权重
w = torch.randn(size=(n, c),  requires_grad=True, dtype=torch.float32)

In [37]:
# 整合信息
z_hat = torch.mm(X, w)
# 加工信息
sigma = torch.softmax(z_hat, dim=1)

In [38]:
sigma

tensor([[9.7232e-01, 2.3609e-02, 4.0667e-03],
        [8.6008e-01, 7.6240e-02, 6.3683e-02],
        [7.7210e-01, 2.4443e-02, 2.0345e-01],
        [4.1000e-04, 6.1172e-01, 3.8787e-01],
        [7.2260e-01, 2.9113e-02, 2.4829e-01],
        [7.9961e-01, 1.1297e-01, 8.7416e-02],
        [8.4914e-01, 1.2141e-01, 2.9452e-02],
        [2.2295e-02, 3.9611e-01, 5.8159e-01],
        [9.2979e-03, 4.0224e-01, 5.8846e-01],
        [1.8620e-03, 9.3091e-01, 6.7230e-02],
        [5.6557e-02, 2.2191e-01, 7.2153e-01],
        [9.9810e-01, 3.1803e-05, 1.8676e-03],
        [1.0296e-02, 1.5393e-03, 9.8816e-01],
        [4.7254e-01, 2.8512e-01, 2.4234e-01],
        [2.4350e-04, 9.9600e-01, 3.7573e-03],
        [7.0799e-03, 9.0332e-01, 8.9595e-02],
        [1.4026e-04, 9.3037e-01, 6.9488e-02],
        [1.0174e-05, 9.9237e-01, 7.6157e-03],
        [9.3553e-01, 3.9643e-02, 2.4823e-02],
        [5.3448e-02, 6.2719e-02, 8.8383e-01],
        [1.6211e-01, 3.9226e-02, 7.9866e-01],
        [9.6225e-01, 1.5265e-03, 3

In [39]:
log_softmax = LogSoftmax(dim=1)
# 对整合信息的结果进行加工, 加工信息的函数是先计算softmax然后计算log
log_sigma = log_softmax(z_hat)

# 计算损失函数的函数值
criterion = NLLLoss()
loss = criterion(log_sigma, y.long())

print(f"当前损失函数的函数值为: {loss}")

当前损失函数的函数值为: 2.6309309005737305


In [40]:
# 计算损失函数的函数值
criterion = CrossEntropyLoss()
loss = criterion(z_hat, y.long())

print(f"当前损失函数的函数值为: {loss}")

当前损失函数的函数值为: 2.6309309005737305
