In [3]:
torch.tensor(1.)

tensor(1.)

In [4]:
# 加载数据
X, y = tensorGenCla()

# 计算一个完整的数据集中样本的个数 => 标量
m = len(X)
m

1500

In [5]:
indices = list(range(m))
indices

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,


In [6]:
random.shuffle(indices)
indices

[699,
 1058,
 239,
 1404,
 1236,
 1115,
 628,
 482,
 102,
 149,
 218,
 195,
 690,
 296,
 125,
 596,
 1013,
 1469,
 516,
 756,
 1191,
 133,
 1259,
 910,
 340,
 778,
 573,
 462,
 303,
 619,
 397,
 1117,
 962,
 450,
 499,
 903,
 67,
 1460,
 478,
 585,
 1332,
 1134,
 955,
 1024,
 849,
 10,
 1269,
 266,
 412,
 696,
 197,
 558,
 818,
 733,
 277,
 1049,
 64,
 391,
 1244,
 822,
 1421,
 554,
 458,
 989,
 483,
 1074,
 726,
 225,
 772,
 59,
 507,
 1365,
 531,
 7,
 686,
 1445,
 840,
 472,
 1400,
 1420,
 694,
 611,
 417,
 1025,
 1167,
 119,
 372,
 988,
 1021,
 1201,
 208,
 1422,
 730,
 161,
 390,
 844,
 687,
 506,
 575,
 835,
 238,
 1363,
 956,
 1145,
 378,
 748,
 574,
 58,
 539,
 1161,
 1077,
 712,
 465,
 1386,
 15,
 202,
 1001,
 1051,
 1256,
 528,
 786,
 50,
 1211,
 746,
 924,
 680,
 224,
 375,
 333,
 718,
 165,
 490,
 944,
 759,
 827,
 1228,
 230,
 1409,
 1113,
 263,
 345,
 1307,
 388,
 1177,
 958,
 193,
 677,
 78,
 1121,
 821,
 358,
 1068,
 1432,
 1034,
 861,
 1262,
 60,
 1295,
 547,
 101,
 946

In [7]:
def train_test_split(X, y, rate=0.7):
    """将一个完整的数据集划分为训练数据集和测试数据集, 数据集包括特征变量和标签
    @param X: 特征变量
    @param y: 标签
    @param rate: 训练数据集占完整数据集的比例
    
    @return X_train, X_test, y_train, y_test: 训练数据集和测试数据集
    """
    # 1.计算一个完整的数据集中样本的个数 => 标量
    m = len(X)
    # 2.在计算机的内存中一次性存储1～500总共500个标量 => 存储在数据结构列表中
    indices = list(range(m))
    # 3.原地in-place打乱样本的索引顺序
    random.shuffle(indices)
    # 4.计算训练数据集中的样本的个数 => 标量
    m_train = int(m * rate)  # 报错: TypeError: slice indices must be integers
    # 5.分别获取训练数据集中样本的索引和测试数据集中样本的索引
    indices_train = torch.tensor(indices[:m_train], dtype=torch.int32)
    indices_test = torch.tensor(indices[m_train:], dtype=torch.int32)
    # 6.在计算机的内存中一次性存储训练数据集中的特征变量和标签
    X_train = X[indices_train]
    y_train = y[indices_train]
    # 7.在计算机的内存中一次性存储测试数据集中的特征变量和标签
    X_test = X[indices_test]
    y_test = y[indices_test]

    return X_train, X_test, y_train, y_test

In [8]:
# 在计算机的内存中一次性存储多个数. 从0-9
f = torch.arange(start=0, end=10, step=1)
f

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
# 在计算机的内存中一次性存储多个数. 从1-10
l = torch.arange(start=1, end=11, step=1)
l

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
train_test_split(X=f, y=l)

(tensor([3, 0, 4, 8, 5, 1, 9]),
 tensor([2, 6, 7]),
 tensor([ 4,  1,  5,  9,  6,  2, 10]),
 tensor([3, 7, 8]))

In [11]:
torch.manual_seed(55)

X, y = tensorGenReg()

In [12]:
X

tensor([[ 1.8616,  0.9035,  1.0000],
        [ 1.3395,  1.2005,  1.0000],
        [ 1.0070,  0.2379,  1.0000],
        ...,
        [-0.0973, -0.4635,  1.0000],
        [ 0.1802, -0.3851,  1.0000],
        [-0.2370, -0.9159,  1.0000]])

In [13]:
torch.manual_seed(55)

# 加载原始数据集
X, y = tensorGenReg()

# 将完整的数据集划分为训练数据集和测试数据集
X_train, X_test, y_train, y_test = train_test_split(X=X, y=y)

In [14]:
torch.manual_seed(55)

# 搭建深度神经网络模型的架构
net = linear_regression

# 实例化模型, 初始化模型的参数
w = torch.zeros(size=(X.shape[1], 1), requires_grad=True)

# 选择合适的损失函数
criterion = squared_loss

# 选择合适的优化器
eta = 0.03

# 搭建深度神经网络模型的训练流程
# =====> 数据部分:
# 1.将一个完整的数据集学习多遍, 设置学习的遍数 => 标量
n_epochs = 5
# 2.每一遍将一个完整的数据集按照一定的大小划分为若干个互不相交的子数据集, 设置子数据集的大小 => 标量
batch_size = 10

# =====> 模型训练部分:
for i_epoch in range(n_epochs):  # 0 1 2 3 4 总共五个数
    # print(i_epoch)
    for (i_X, i_y) in split_dataset(batch_size=batch_size, X=X_train, y=y_train):
        # 前向传播, 计算当前模型在当前参数设置下的预测输出标记
        z_hat = net(i_X, w)
        # 计算损失, 计算预测输出标记和真实标签之间的误差. 构建完整的计算图
        loss = criterion(z_hat, i_y)
        # 反向传播, 计算当前模型的所有参数在当前参数取值下的偏导函数信息
        loss.backward()
        # 参数更新, 优化器借助反向传播提供的信息, 按照一定的规则更新模型的所有参数的取值
        stochastic_gradient_descent(params=w, lr=eta)

In [15]:
# 获取训练完成的模型的参数
w

tensor([[ 1.9997],
        [-1.0004],
        [ 1.0005]], requires_grad=True)

In [16]:
# 计算训练完成的模型在训练数据集上的损失函数的取值
loss_train = criterion(net(X_train, w), y_train)
loss_train

tensor(9.3047e-05, grad_fn=<DivBackward0>)

In [17]:
# 计算训练完成的模型在测试数据集上的损失函数的取值
loss_test = criterion(net(X_test, w), y_test)
loss_test

tensor(0.0001, grad_fn=<DivBackward0>)

In [1]:
# 加载模块中的函数
from torch.utils.data import random_split

In [19]:
# 在计算机的内存中一次性存储多个数值. e.g. 从0-11  选择数据结构张量 => 二维张量, 形状是四行三列
t = torch.arange(start=0, end=12, step=1).reshape(4, 3)
t

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [20]:
random_split(dataset=t, lengths=[2, 2])

In [21]:
train, test = random_split(dataset=t, lengths=[2, 2])

In [22]:
type(train)

torch.utils.data.dataset.Subset

In [23]:
for train, test in random_split(dataset=t, lengths=[2, 2]):
    print(train)
    print(test)

tensor([3, 4, 5])
tensor([0, 1, 2])
tensor([ 9, 10, 11])
tensor([6, 7, 8])


In [24]:
# 加载模块中的类
from torch.utils.data import Dataset, DataLoader

In [25]:
# 加载数据集
X, y = tensorGenReg(bias=False)

In [26]:
X

tensor([[-0.2462, -0.3578, -0.1369],
        [ 0.9560,  1.0662, -1.0513],
        [-1.7488, -0.8720,  0.5953],
        ...,
        [ 1.3293,  2.3669, -0.5442],
        [ 1.0400, -1.4623,  0.0896],
        [ 0.9643, -0.8364,  1.2889]])

In [27]:
# 使用TensorDataset是因为想将特征变量和标签打包放在一个元组中
dataset = TensorDataset(X, y)
dataset

In [28]:
# TensorDataset类的paramter只能接受多个tensor数据类型的数据
TensorDataset([1, 2], 1)

AttributeError: 'list' object has no attribute 'size'

In [29]:
TensorDataset?

Init signature: TensorDataset(*tensors: torch.Tensor) -> None
Docstring:     
Dataset wrapping tensors.

Each sample will be retrieved by indexing tensors along the first dimension.

Args:
    *tensors (Tensor): tensors that have the same size of the first dimension.
File:           ~/Documents/computational_biology/anaconda/anaconda3/envs/DL/lib/python3.10/site-packages/torch/utils/data/dataset.py
Type:           type
Subclasses:     

In [30]:
# 加载Scikit-learn项目的内置数据集
from sklearn.datasets import load_breast_cancer

dataset = load_breast_cancer()

In [31]:
# 查看数据集中的特征矩阵
dataset.data

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [32]:
# 查看数据集中的标签
dataset.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [33]:
# 计算数据集中样本的个数 => 标量
m = len(dataset.data)
m

569

In [34]:
# 通过非PyTorch模块加载数据集. e.g. 通过Scikit-learn模块
from sklearn.datasets import load_breast_cancer

ml_dataset = load_breast_cancer()

In [35]:
# 将通过非PyTorch模块加载的数据集 转换为 PyTorch模块在搭建深度神经网络模型训练过程时使用的数据集
class LBCDataset(Dataset):
    # 构造器 + 类/成员属性
    # => 子类的对象调用父类的构造器
    def __init__(self, dataset):
        self.X = dataset.data
        self.y = dataset.target
        self.m = len(dataset.data)
        
    # 方法
    def __getitem__(self, index):
        return self.X[index, :], self.y[index]

    def __len__(self):
        return self.m

In [36]:
dl_dataset = LBCDataset(dataset=ml_dataset)

In [37]:
# 深度机器学习中的数据集
dl_dataset.X

array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]])

In [38]:
dl_dataset.y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [39]:
dl_dataset.m

569

In [40]:
dl_dataset.__getitem__(index=2)

(array([1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 1.599e-01,
        1.974e-01, 1.279e-01, 2.069e-01, 5.999e-02, 7.456e-01, 7.869e-01,
        4.585e+00, 9.403e+01, 6.150e-03, 4.006e-02, 3.832e-02, 2.058e-02,
        2.250e-02, 4.571e-03, 2.357e+01, 2.553e+01, 1.525e+02, 1.709e+03,
        1.444e-01, 4.245e-01, 4.504e-01, 2.430e-01, 3.613e-01, 8.758e-02]),
 0)

In [41]:
dl_dataset[2]

(array([1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 1.599e-01,
        1.974e-01, 1.279e-01, 2.069e-01, 5.999e-02, 7.456e-01, 7.869e-01,
        4.585e+00, 9.403e+01, 6.150e-03, 4.006e-02, 3.832e-02, 2.058e-02,
        2.250e-02, 4.571e-03, 2.357e+01, 2.553e+01, 1.525e+02, 1.709e+03,
        1.444e-01, 4.245e-01, 4.504e-01, 2.430e-01, 3.613e-01, 8.758e-02]),
 0)

In [42]:
dl_dataset.X[2]

array([1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 1.599e-01,
       1.974e-01, 1.279e-01, 2.069e-01, 5.999e-02, 7.456e-01, 7.869e-01,
       4.585e+00, 9.403e+01, 6.150e-03, 4.006e-02, 3.832e-02, 2.058e-02,
       2.250e-02, 4.571e-03, 2.357e+01, 2.553e+01, 1.525e+02, 1.709e+03,
       1.444e-01, 4.245e-01, 4.504e-01, 2.430e-01, 3.613e-01, 8.758e-02])

In [43]:
dl_dataset.y[2]

0

In [44]:
dl_dataset[:]

(array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]]),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [45]:
# 有一个完整的数据集, 计算数据集中样本的个数 => 标量
m = len(dl_dataset)
m

569

In [46]:
# 如果按照训练数据集样本数占总样本数的70%, 剩余30%为测试数据集样本数
rate = 0.7
# 1.计算训练数据集中的样本数
m_train = int(m * rate)
m_train
# 2.计算测试数据集中的样本数. 训练数据集中的样本数+测试数据集中的样本数=完整数据集中的样本数
m_test = m - m_train
m_test

398

171

In [47]:
dl_dataset_train, dl_dataset_test = random_split(dataset=dl_dataset, lengths=[m_train, m_test])

In [48]:
random_split?

Signature:
random_split(
    dataset: torch.utils.data.dataset.Dataset[~T],
    lengths: Sequence[Union[int, float]],
    generator: Optional[torch._C.Generator] = <torch._C.Generator object at 0x11e20c550>,
) -> List[torch.utils.data.dataset.Subset[~T]]
Docstring:
Randomly split a dataset into non-overlapping new datasets of given lengths.

If a list of fractions that sum up to 1 is given,
the lengths will be computed automatically as
floor(frac * len(dataset)) for each fraction provided.

After computing the lengths, if there are any remainders, 1 count will be
distributed in round-robin fashion to the lengths
until there are no remainders left.

Optionally fix the generator for reproducible results, e.g.:

Example:
    >>> # xdoctest: +SKIP
    >>> generator1 = torch.Generator().manual_seed(42)
    >>> generator2 = torch.Generator().manual_seed(42)
    >>> random_split(range(10), [3, 7], generator=generator1)
    >>> random_split(range(30), [0.3, 0.3, 0.4], generator=generator2)

Ar

In [49]:
dl_dataset_train.dataset

In [50]:
dl_dataset_train.indices

[413,
 105,
 235,
 176,
 449,
 393,
 104,
 230,
 383,
 192,
 44,
 43,
 97,
 63,
 48,
 7,
 421,
 258,
 164,
 227,
 274,
 271,
 328,
 300,
 507,
 160,
 234,
 145,
 273,
 409,
 322,
 245,
 499,
 319,
 149,
 251,
 332,
 214,
 500,
 491,
 401,
 287,
 386,
 270,
 151,
 228,
 16,
 407,
 361,
 505,
 496,
 343,
 94,
 476,
 396,
 439,
 15,
 454,
 461,
 111,
 47,
 188,
 294,
 538,
 252,
 399,
 291,
 283,
 114,
 150,
 357,
 560,
 46,
 66,
 297,
 548,
 200,
 410,
 285,
 502,
 329,
 381,
 464,
 62,
 136,
 241,
 545,
 8,
 309,
 45,
 205,
 430,
 471,
 275,
 369,
 355,
 312,
 327,
 103,
 194,
 148,
 497,
 253,
 390,
 85,
 165,
 244,
 444,
 565,
 451,
 125,
 354,
 462,
 36,
 23,
 384,
 299,
 232,
 350,
 561,
 147,
 184,
 338,
 1,
 517,
 514,
 42,
 187,
 59,
 108,
 448,
 254,
 304,
 286,
 50,
 537,
 478,
 412,
 73,
 387,
 100,
 406,
 223,
 246,
 177,
 453,
 318,
 154,
 219,
 415,
 14,
 236,
 33,
 482,
 78,
 222,
 190,
 442,
 368,
 306,
 434,
 34,
 534,
 563,
 84,
 170,
 175,
 542,
 19,
 109,
 310,
 556,


In [51]:
len(dl_dataset_train.indices)

398

In [52]:
dl_dataset_train.dataset == dl_dataset

True

In [53]:
for sample in dl_dataset_train:
    print(sample)
    break

(array([1.499e+01, 2.211e+01, 9.753e+01, 6.937e+02, 8.515e-02, 1.025e-01,
       6.859e-02, 3.876e-02, 1.944e-01, 5.913e-02, 3.186e-01, 1.336e+00,
       2.310e+00, 2.851e+01, 4.449e-03, 2.808e-02, 3.312e-02, 1.196e-02,
       1.906e-02, 4.015e-03, 1.676e+01, 3.155e+01, 1.102e+02, 8.671e+02,
       1.077e-01, 3.345e-01, 3.114e-01, 1.308e-01, 3.163e-01, 9.251e-02]), 1)


In [54]:
for sample in dl_dataset_train.dataset:
    print(sample)
    break

(array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01]), 0)


In [55]:
for index in dl_dataset_train.indices:
    print(index)
    break

413


In [56]:
for sample in dl_dataset:
    print(sample)
    break

(array([1.799e+01, 1.038e+01, 1.228e+02, 1.001e+03, 1.184e-01, 2.776e-01,
       3.001e-01, 1.471e-01, 2.419e-01, 7.871e-02, 1.095e+00, 9.053e-01,
       8.589e+00, 1.534e+02, 6.399e-03, 4.904e-02, 5.373e-02, 1.587e-02,
       3.003e-02, 6.193e-03, 2.538e+01, 1.733e+01, 1.846e+02, 2.019e+03,
       1.622e-01, 6.656e-01, 7.119e-01, 2.654e-01, 4.601e-01, 1.189e-01]), 0)


In [57]:
dl_dataset.__getitem__(384)

(array([1.328e+01, 1.372e+01, 8.579e+01, 5.418e+02, 8.363e-02, 8.575e-02,
        5.077e-02, 2.864e-02, 1.617e-01, 5.594e-02, 1.833e-01, 5.308e-01,
        1.592e+00, 1.526e+01, 4.271e-03, 2.073e-02, 2.828e-02, 8.468e-03,
        1.461e-02, 2.613e-03, 1.424e+01, 1.737e+01, 9.659e+01, 6.237e+02,
        1.166e-01, 2.685e-01, 2.866e-01, 9.173e-02, 2.736e-01, 7.320e-02]),
 1)

In [58]:
dl_dataset[dl_dataset_train.indices]  # 获取所有的训练数据集中的样本

(array([[1.499e+01, 2.211e+01, 9.753e+01, ..., 1.308e-01, 3.163e-01,
         9.251e-02],
        [1.311e+01, 1.556e+01, 8.721e+01, ..., 1.986e-01, 3.147e-01,
         1.405e-01],
        [1.403e+01, 2.125e+01, 8.979e+01, ..., 7.963e-02, 2.226e-01,
         7.617e-02],
        ...,
        [1.754e+01, 1.932e+01, 1.151e+02, ..., 1.939e-01, 2.928e-01,
         7.867e-02],
        [1.324e+01, 2.013e+01, 8.687e+01, ..., 1.357e-01, 2.845e-01,
         1.249e-01],
        [1.625e+01, 1.951e+01, 1.098e+02, ..., 1.775e-01, 3.318e-01,
         9.136e-02]]),
 array([1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1,
        1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0,
        1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0,
        1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0,
 

In [59]:
len(dl_dataset_train.indices)

398

In [60]:
DataLoader?

Init signature:
DataLoader(
    dataset: torch.utils.data.dataset.Dataset[+T_co],
    batch_size: Optional[int] = 1,
    shuffle: Optional[bool] = None,
    sampler: Union[torch.utils.data.sampler.Sampler, Iterable, NoneType] = None,
    batch_sampler: Union[torch.utils.data.sampler.Sampler[List], Iterable[List], NoneType] = None,
    num_workers: int = 0,
    collate_fn: Optional[Callable[[List[~T]], Any]] = None,
    pin_memory: bool = False,
    drop_last: bool = False,
    timeout: float = 0,
    worker_init_fn: Optional[Callable[[int], NoneType]] = None,
    multiprocessing_context=None,
    generator=None,
    *,
    prefetch_factor: Optional[int] = None,
    persistent_workers: bool = False,
    pin_memory_device: str = '',
)
Docstring:     
Data loader combines a dataset and a sampler, and provides an iterable over the given dataset.

The :class:`~torch.utils.data.DataLoader` supports both map-style and
iterable-style datasets with single- or multi-process loading, customizing


In [61]:
# 将一个完整的训练数据集按照指定的大小划分为若干个互不相交的子数据集
batched_dl_dataset_train = DataLoader(dataset=dl_dataset_train, batch_size=10, shuffle=True)

In [62]:
# 将一个完整的测试数据集按照指定的大小划分为若干个互不相交的子数据集
batched_dl_dataset_test = DataLoader(dataset=dl_dataset_test, batch_size=10, shuffle=False)

In [64]:
for sample in dl_dataset_train:
    print(sample)
    break

(array([1.499e+01, 2.211e+01, 9.753e+01, 6.937e+02, 8.515e-02, 1.025e-01,
       6.859e-02, 3.876e-02, 1.944e-01, 5.913e-02, 3.186e-01, 1.336e+00,
       2.310e+00, 2.851e+01, 4.449e-03, 2.808e-02, 3.312e-02, 1.196e-02,
       1.906e-02, 4.015e-03, 1.676e+01, 3.155e+01, 1.102e+02, 8.671e+02,
       1.077e-01, 3.345e-01, 3.114e-01, 1.308e-01, 3.163e-01, 9.251e-02]), 1)


In [66]:
batched_dl_dataset_test.dataset == dl_dataset_train

False

In [3]:
torch.manual_seed(55)

# 加载数据
# =====> 1.加载完整的原始数据集(通过非PyTorch模块的方式加载): 特征变量+标签
X, y = tensorGenReg()
X = X[:, :-1]

# =====> 2.将完整的原始数据集以PyTorch模块的方式加载
class tensorGenRegDataset(Dataset):  # 以数据集的名称Dataset命名该类
    # 构造器 + 类/对象属性
    # => 子类的对象调用父类的构造器
    # => 在数据存储在类/对象数据字典中
    def __init__(self, X, y):
        self.X = X
        self.y = y
        # 计算一个完整的数据集中的样本的个数 => 标量scalar
        self.m = len(X)

    # 方法
    # => 重写__getitem__(self, index)方法
    # => 重写__len(self)__方法
    def __getitem__(self, index):
        """根据样本的编号, 返回样本的特征变量和标签
        @param index: 样本的编号
        @return 样本的特征变量和标签, 存储在元组数据集结构中
        """
        return self.X[index, :], self.y[index]

    def __len__(self):
        """返回完整数据集中样本的个数
        """
        return self.m

tensorGenReg_dataset = tensorGenRegDataset(X=X, y=y)

# =====> 3.将完整的原始数据集按照一定的比例划分为训练数据集和测试数据集
# 在计算机的内存中存储一个数值, 代表训练数据集中的样本数占总样本数的比例
rate = 0.7
# 计算训练数据集中的样本的个数 = 完整的数据集中的样本的个数 * 百分比 => 一个整数
m_train = int(tensorGenReg_dataset.m * rate)
# 计算测试数据集中的样本的个数 = 完整的数据集中的样本的个数 - 训练数据集中的样本的个数
m_test = tensorGenReg_dataset.m - m_train
# 划分
tensorGenReg_dataset_train, tensorGenReg_dataset_test = random_split(dataset=tensorGenReg_dataset, lengths=[m_train, m_test])

# =====> 4.分别对训练数据集和测试数据集按照一定的样本容量划分为若干个互不相交的子数据集
batch_size = 10
batched_tensorGenReg_dataset_train = DataLoader(dataset=tensorGenReg_dataset_train, batch_size=batch_size, shuffle=True, drop_last=False)
batched_tensorGenReg_dataset_test = DataLoader(dataset=tensorGenReg_dataset_test, batch_size=batch_size, shuffle=False, drop_last=False)

In [4]:
torch.manual_seed(55)

# 搭建深度神经网络模型的架构
# 搭建模型: 使用面向对象(定义类/创建对象)的方式 继承nn.Module类
class GeoffNet(nn.Module):
    
    # 构造器 + 类/对象属性
    # => 子类的对象调用父类的构造器
    # => 神经网络模型中的各种层
    def __init__(self, in_features=2, out_features=1):
        super(GeoffNet, self).__init__()

        self.output_linear = nn.Linear(in_features=in_features, out_features=out_features)
    
    # 方法
    # => 前向传播: 数据从神经网络的输入层 -> 隐藏层 -> 输出层; 逐层完成整合信息+加工信息
    def forward(self, X):
        # 输入层 -> 输出层
        # 1.整合信息
        z_hat = self.output_linear(X)  # 完成当前层上的计算过程
        # 2.加工信息
        return z_hat

# 实例化模型
net = GeoffNet()

In [70]:
torch.manual_seed(55)

# 搭建深度神经网络模型的训练流程
def fit(n_epochs, batched_dataset, model, criterion, optimizer):
    """让模型拟合数据, 在训练过程中更新模型的参数, 使得损失函数值减小, 尽可能最小
    @param n_epochs: 对于一个完整的数据集进行学习的遍数
    @param batched_dataset: 将一个完整的数据集按照指定的样本容量划分为若干个互不相交的子集
    @param model: 模型
    @param criterion: 损失函数
    @param optimizer: 优化器

    @return: 完成训练流程的模型(不一定是性能最好的模型)
    """
    for i_epoch in range(n_epochs):
        for (i_X, i_y) in batched_dataset:
            # 1.前向传播, 计算以当前的模型参数对该批次的数据进行学习, 模型的预测输出标记
            z_hat = model.forward(i_X)
            # 2.计算损失, 计算模型的预测输出标记与真实标签之间的误差, 构建完整的计算图
            loss = criterion(z_hat, i_y)
            # 3.反向传播, 计算以当前的模型参数对应的偏导函数表达式和值, 以确定各个模型的参数在对应维度上应该向哪个方向进行更新(该维度所在的正方向or负方向)
            loss.backward()
            # 4.更新模型的参数, 优化器根据梯度信息, 计算当前的模型参数在各个维度的已知方向上应该更新的数值
            optimizer.step()
            # 5.清空梯度信息
            optimizer.zero_grad()

# =====> 1.选择合适的损失函数. 按照一定的公式计算模型的预测输出标记和真实标签之间的误差+构造完整的计算图
criterion = nn.MSELoss()
# =====> 2.选择合适的优化器. 借助反向传播计算的梯度信息, 按照一定的公式更新模型中全部的参数
eta = 0.03  # 学习率
optimizer = optim.SGD(params=net.parameters(), lr=eta)
# =====> 3.开始训练
n_epochs = 3
fit(n_epochs=n_epochs, batched_dataset=batched_tensorGenReg_dataset_train,
   model=net, criterion=criterion, optimizer=optimizer)

In [71]:
# 获取训练完的模型
net

GeoffNet(
  (output_linear): Linear(in_features=2, out_features=1, bias=True)
)

In [72]:
# 获取训练完的模型的参数
list(net.parameters())

[Parameter containing:
 tensor([[ 2.0007, -1.0008]], requires_grad=True),
 Parameter containing:
 tensor([1.0003], requires_grad=True)]

In [73]:
# 获取训练数据集中所有样本的索引
tensorGenReg_dataset_train.indices

[542,
 332,
 688,
 949,
 502,
 286,
 7,
 275,
 219,
 729,
 842,
 650,
 925,
 960,
 405,
 85,
 528,
 685,
 455,
 82,
 519,
 262,
 566,
 41,
 796,
 48,
 198,
 706,
 485,
 98,
 258,
 702,
 12,
 492,
 128,
 489,
 670,
 149,
 999,
 524,
 689,
 606,
 178,
 181,
 562,
 971,
 967,
 785,
 824,
 622,
 520,
 869,
 411,
 279,
 819,
 69,
 583,
 372,
 775,
 899,
 71,
 289,
 132,
 65,
 348,
 676,
 441,
 601,
 772,
 211,
 472,
 776,
 717,
 257,
 944,
 312,
 878,
 814,
 855,
 458,
 773,
 155,
 883,
 710,
 591,
 995,
 315,
 43,
 304,
 152,
 251,
 470,
 554,
 613,
 180,
 370,
 298,
 732,
 106,
 491,
 795,
 193,
 532,
 529,
 247,
 422,
 323,
 417,
 316,
 89,
 895,
 983,
 169,
 513,
 941,
 408,
 317,
 120,
 335,
 134,
 23,
 700,
 699,
 957,
 40,
 927,
 148,
 445,
 20,
 483,
 2,
 567,
 256,
 660,
 100,
 826,
 260,
 897,
 476,
 604,
 667,
 715,
 639,
 816,
 868,
 531,
 345,
 537,
 272,
 759,
 594,
 937,
 890,
 704,
 296,
 26,
 299,
 549,
 294,
 782,
 480,
 901,
 305,
 13,
 403,
 774,
 803,
 708,
 99,
 993,
 

In [74]:
# 从完整的数据集中通过训练数据集中样本的索引, 获取训练数据集
tensorGenReg_dataset[tensorGenReg_dataset_train.indices]

(tensor([[ 0.1662,  0.2457],
         [-2.3092,  2.1917],
         [-0.2503,  1.6936],
         ...,
         [ 0.8131,  0.9148],
         [-0.9485, -0.1682],
         [ 2.0251,  0.3138]]),
 tensor([[ 1.0714e+00],
         [-5.8087e+00],
         [-1.1851e+00],
         [-1.1667e+00],
         [-1.5329e-01],
         [-6.9076e-01],
         [ 2.5107e+00],
         [ 3.9561e-01],
         [ 3.6936e-01],
         [ 3.5472e+00],
         [ 9.5464e-02],
         [ 1.4143e+00],
         [ 1.3076e-01],
         [-4.5490e-01],
         [ 3.9121e+00],
         [ 3.8458e+00],
         [-1.1381e+00],
         [ 6.2457e-01],
         [-1.1852e+00],
         [ 1.2691e+00],
         [ 3.4679e-01],
         [ 1.9744e+00],
         [-8.0819e-01],
         [ 7.6100e-01],
         [ 5.9529e-01],
         [-7.8521e-01],
         [ 2.8575e+00],
         [-1.4335e+00],
         [ 2.9601e-01],
         [-1.4679e-01],
         [ 2.9899e-01],
         [ 2.9045e+00],
         [ 2.9154e+00],
         [ 4.8962e

In [75]:
type(tensorGenReg_dataset[tensorGenReg_dataset_train.indices])

tuple

In [76]:
len(tensorGenReg_dataset[tensorGenReg_dataset_train.indices])

2

In [77]:
# 获取训练数据集的特征变量
tensorGenReg_dataset[tensorGenReg_dataset_train.indices][0]

tensor([[ 0.1662,  0.2457],
        [-2.3092,  2.1917],
        [-0.2503,  1.6936],
        ...,
        [ 0.8131,  0.9148],
        [-0.9485, -0.1682],
        [ 2.0251,  0.3138]])

In [78]:
# 获取训练数据集的标签
tensorGenReg_dataset[tensorGenReg_dataset_train.indices][1]

tensor([[ 1.0714e+00],
        [-5.8087e+00],
        [-1.1851e+00],
        [-1.1667e+00],
        [-1.5329e-01],
        [-6.9076e-01],
        [ 2.5107e+00],
        [ 3.9561e-01],
        [ 3.6936e-01],
        [ 3.5472e+00],
        [ 9.5464e-02],
        [ 1.4143e+00],
        [ 1.3076e-01],
        [-4.5490e-01],
        [ 3.9121e+00],
        [ 3.8458e+00],
        [-1.1381e+00],
        [ 6.2457e-01],
        [-1.1852e+00],
        [ 1.2691e+00],
        [ 3.4679e-01],
        [ 1.9744e+00],
        [-8.0819e-01],
        [ 7.6100e-01],
        [ 5.9529e-01],
        [-7.8521e-01],
        [ 2.8575e+00],
        [-1.4335e+00],
        [ 2.9601e-01],
        [-1.4679e-01],
        [ 2.9899e-01],
        [ 2.9045e+00],
        [ 2.9154e+00],
        [ 4.8962e+00],
        [ 1.5278e+00],
        [ 2.7776e+00],
        [ 5.1009e-01],
        [-6.8856e-01],
        [ 1.4574e+00],
        [ 2.2495e+00],
        [ 1.1635e+00],
        [-2.3283e+00],
        [ 3.8616e+00],
        [-8

In [80]:
# 获取测试数据集中所有样本的索引
tensorGenReg_dataset_test.indices

[891,
 309,
 94,
 350,
 137,
 164,
 515,
 791,
 942,
 965,
 276,
 385,
 54,
 73,
 574,
 104,
 435,
 657,
 196,
 124,
 434,
 753,
 589,
 138,
 933,
 413,
 787,
 994,
 808,
 874,
 936,
 357,
 572,
 573,
 325,
 584,
 457,
 159,
 346,
 646,
 92,
 675,
 707,
 29,
 642,
 712,
 301,
 577,
 303,
 423,
 656,
 466,
 853,
 52,
 789,
 358,
 948,
 624,
 361,
 845,
 302,
 145,
 462,
 709,
 158,
 225,
 684,
 972,
 894,
 115,
 226,
 793,
 886,
 911,
 93,
 412,
 811,
 964,
 962,
 666,
 817,
 33,
 608,
 113,
 866,
 28,
 940,
 167,
 469,
 663,
 747,
 757,
 59,
 375,
 569,
 621,
 67,
 614,
 620,
 959,
 902,
 474,
 136,
 560,
 254,
 74,
 539,
 140,
 14,
 961,
 21,
 31,
 326,
 278,
 588,
 87,
 241,
 130,
 605,
 331,
 188,
 593,
 197,
 453,
 415,
 784,
 951,
 815,
 144,
 833,
 888,
 643,
 380,
 266,
 788,
 798,
 550,
 264,
 25,
 514,
 103,
 432,
 4,
 922,
 917,
 698,
 440,
 838,
 235,
 543,
 58,
 763,
 64,
 404,
 208,
 126,
 984,
 627,
 341,
 482,
 353,
 204,
 259,
 556,
 988,
 320,
 477,
 222,
 512,
 414,
 

In [81]:
# 计算测试数据集中的样本的个数
m_test
len(tensorGenReg_dataset_test.indices)

300

300

In [83]:
# 从完整的数据集中获取测试数据集的特征变量
type(tensorGenReg_dataset[tensorGenReg_dataset_test.indices])
tensorGenReg_dataset[tensorGenReg_dataset_test.indices][0]

tuple

tensor([[ 5.8211e-02, -5.1450e-02],
        [ 4.6462e-01,  1.3366e+00],
        [-6.1968e-01,  2.2003e+00],
        [ 4.3708e-01,  1.0480e+00],
        [-5.8773e-01,  1.1988e+00],
        [-1.1467e+00,  1.6580e+00],
        [ 4.8640e-01, -1.4378e+00],
        [-3.2476e-01, -4.4531e-01],
        [ 3.4006e-02,  8.9708e-01],
        [ 2.3880e+00,  7.6120e-02],
        [ 3.0358e-01, -7.1283e-01],
        [ 1.8411e+00, -1.2790e-01],
        [ 2.2414e+00, -1.7890e-01],
        [ 1.3317e-01, -8.2861e-02],
        [ 1.5354e+00,  1.6788e-01],
        [ 1.0467e+00, -2.0846e+00],
        [ 4.7122e-01,  1.3181e+00],
        [-5.1967e-01,  7.2717e-02],
        [-6.6854e-01,  2.5426e-01],
        [ 4.0616e-01, -1.1293e+00],
        [-5.9000e-01, -5.9733e-02],
        [-6.0702e-01,  1.8217e+00],
        [ 2.5376e+00, -1.0975e+00],
        [ 1.4540e+00, -6.2552e-01],
        [ 1.4293e+00, -1.4599e+00],
        [ 1.4707e+00, -1.5748e-01],
        [ 8.2696e-01, -1.0996e+00],
        [-3.7688e-01, -7.646

In [84]:
# 从完整的数据集中获取测试数据集的标签
tensorGenReg_dataset[tensorGenReg_dataset_test.indices][1]

tensor([[ 1.1620e+00],
        [ 6.0929e-01],
        [-2.4364e+00],
        [ 8.2079e-01],
        [-1.3746e+00],
        [-2.9598e+00],
        [ 3.4135e+00],
        [ 8.0084e-01],
        [ 1.6233e-01],
        [ 5.6999e+00],
        [ 2.3170e+00],
        [ 4.8210e+00],
        [ 5.6624e+00],
        [ 1.3540e+00],
        [ 3.9118e+00],
        [ 5.1700e+00],
        [ 6.1217e-01],
        [-1.1722e-01],
        [-5.8309e-01],
        [ 2.9415e+00],
        [-1.0880e-01],
        [-2.0310e+00],
        [ 7.1820e+00],
        [ 4.5214e+00],
        [ 5.3191e+00],
        [ 4.1136e+00],
        [ 3.7490e+00],
        [ 1.0243e+00],
        [-9.0587e-03],
        [-1.9143e+00],
        [-1.1169e-01],
        [ 1.2634e+00],
        [ 2.0642e+00],
        [-2.9665e+00],
        [ 1.4585e+00],
        [ 1.9635e+00],
        [ 3.6952e+00],
        [-2.0270e-01],
        [ 1.8054e+00],
        [ 3.9434e+00],
        [ 4.9823e+00],
        [ 2.5413e+00],
        [-2.3590e+00],
        [ 5

In [79]:
# 计算完成训练后的模型在训练数据集上的损失函数
loss_train = criterion(net(tensorGenReg_dataset[tensorGenReg_dataset_train.indices][0]), tensorGenReg_dataset[tensorGenReg_dataset_train.indices][1])
loss_train

tensor(9.7497e-05, grad_fn=<MseLossBackward0>)

In [85]:
# 计算完成训练后的模型在测试数据集上的损失函数
loss_test = criterion(net(tensorGenReg_dataset[tensorGenReg_dataset_test.indices][0]), tensorGenReg_dataset[tensorGenReg_dataset_test.indices][1])
loss_test

tensor(8.8828e-05, grad_fn=<MseLossBackward0>)

In [5]:
from torch.utils.data import random_split

def split_loader(X, y, rate=0.7, batch_size=10):
    """
    先将一个完整的数据集按照给定的比例划分为训练数据集和测试数据集
    再将训练数据集和测试数据集分别按照给定的大小分别划分为互不相交的子集合
    @param X: 特征变量
    @param y: 标签
    @param rate: 训练数据集中的样本数占完整数据集中的样本数的比例
    @param batch_size: 用于划分子集合的数据集的大小

    @return 批处理化后的训练数据集和测试数据集
    """
    # 1.计算一个完整的数据集包含的样本个数 => 标量
    m = len(X)
    # 2.计算训练数据集中包含的样本的个数 = 完整的数据集中包含的样本的个数 * 训练数据集中的样本数占完整数据集中的样本数的比例
    m_train = int(m * rate)
    # 3.计算测试数据集中包含的样本的个数 = 完整的数据集中包含的样本的个素 - 训练数据集中的样本数
    m_test = m - m_train
    # 4.将一个完整的数据集按照给定的比例划分为训练数据集和测试数据集
    dataset = tensorGenRegDataset(X=X, y=y)
    dataset_train, dataset_test = random_split(dataset=dataset, lengths=[m_train, m_test])

    # 5.将训练数据集和测试数据集分别按照给定的大小分别划分为互不相交的子集合
    batched_dataset_train = DataLoader(dataset=dataset_train, batch_size=batch_size, shuffle=True)
    batched_dataset_test = DataLoader(dataset=dataset_test, batch_size=batch_size, shuffle=False)

    return batched_dataset_train, batched_dataset_test

In [7]:
torch.manual_seed(55)

# 加载原始的数据集
X, y = tensorGenReg()
X = X[:, :-1]

# 加载批处理后的训练数据集和测试数据集
batched_dataset_train, batched_dataset_test = split_loader(X=X, y=y)

In [8]:
type(batched_dataset_train)

torch.utils.data.dataloader.DataLoader

In [10]:
batched_dataset_train.dataset[0]

(tensor([0.1662, 0.2457]), tensor([1.0714]))

In [13]:
# 查看训练数据集中样本的个数
# len(batched_dataset_train.dataset[:])
len(batched_dataset_train.dataset[:][0])

700

In [10]:
def calc_mse(dataset, model):
    """对一个完成训练流程的模型, 计算模型在训练数据集或测试数据集上的MSE
    @param dataset: 训练数据集or测试数据集
    @param model: 一个已经完成训练流程的模型
    """
    # 1.从完整的数据集中获取样本的特征变量和标签
    X = dataset.dataset[:][0]
    y = dataset.dataset[:][1]
    # 2.前向传播, 计算模型以当前的参数对数据集进行学习后的预测输出标记
    z_hat = model.forward(X)
    # 3.计算损失, 计算模型的预测输出标记和真实标签之间的误差
    loss = F.mse_loss(z_hat, y)
    return loss

In [15]:
batched_dataset_train.dataset[:][0]

tensor([[ 0.1662,  0.2457],
        [-2.3092,  2.1917],
        [-0.2503,  1.6936],
        ...,
        [ 0.8131,  0.9148],
        [-0.9485, -0.1682],
        [ 2.0251,  0.3138]])

In [6]:
def fit(n_epochs, batched_dataset, model, criterion, optimizer, task="reg"):
        """让模型拟合数据, 在训练过程中更新模型的参数, 使得损失函数值减小, 尽可能最小
        @param n_epochs: 对于一个完整的数据集进行学习的遍数
        @param batched_dataset: 将一个完整的数据集按照指定的样本容量划分为若干个互不相交的子集
        @param model: 模型
        @param criterion: 损失函数
        @param optimizer: 优化器

        @return: 完成训练流程的模型(不一定是性能最好的模型)
        """
        for i_epoch in range(n_epochs):
            for (i_X, i_y) in batched_dataset:
                # 1.前向传播, 计算以当前的模型参数对该批次的数据进行学习, 模型的预测输出标记
                z_hat = model.forward(i_X)
                # 2.计算损失, 计算模型的预测输出标记与真实标签之间的误差, 构建完整的计算图
                if task == "clf":
                    i_y = i_y.flatten().long()
                    
                loss = criterion(z_hat, i_y)
                # 3.反向传播, 计算以当前的模型参数对应的偏导函数表达式和值, 以确定各个模型的参数在对应维度上应该向哪个方向进行更新(该维度所在的正方向or负方向)
                loss.backward()
                # 4.更新模型的参数, 优化器根据梯度信息, 计算当前的模型参数在各个维度的已知方向上应该更新的数值
                optimizer.step()
                # 5.清空梯度信息
                optimizer.zero_grad()

In [7]:
torch.manual_seed(55)

# 加载原始的数据集
X, y = tensorGenReg()
X = X[:, :-1]

# 加载批处理后的训练数据集和测试数据集
batched_dataset_train, batched_dataset_test = split_loader(X=X, y=y)

# 实例化模型
net

# 选择合适的损失函数
criterion = nn.MSELoss()

# 选择合适的优化器
eta = 0.03
optimizer = optim.SGD(params=net.parameters(), lr=eta)

# 训练模型
fit(n_epochs=3, batched_dataset=batched_dataset_train, model=net, criterion=criterion, optimizer=optimizer)

GeoffNet(
  (output_linear): Linear(in_features=2, out_features=1, bias=True)
)

In [9]:
# 查看完成训练的模型
net

GeoffNet(
  (output_linear): Linear(in_features=2, out_features=1, bias=True)
)

In [12]:
# 计算完成训练的模型在训练数据集上的损失函数的数值
calc_mse(dataset=batched_dataset_train, model=net)

tensor(9.7814e-05, grad_fn=<MseLossBackward0>)

In [18]:
# type(batched_dataset_train.dataset[0])
# len(batched_dataset_train.dataset[:][0])
len(batched_dataset_train.dataset[:])

2

In [13]:
# 计算完成训练的模型在测试数据集上的损失函数的数值
calc_mse(dataset=batched_dataset_test, model=net)

tensor(8.9001e-05, grad_fn=<MseLossBackward0>)

In [19]:
def calc_accuracy(dataset, model):
    """对一个完成训练的模型, 计算模型在训练数据集或者测试数据集上的分类准确度
    @param dataset: 训练数据集或者测试数据集
    @param model: 完成训练的模型
    @return 模型在训练数据集或者测试数据集上的分类准确度
    """
    # 1.计算数据集中样本的总数
    # m = len(dataset.dataset[:][0])
    # 2.计算模型在当前数据集上的预测输出标记
    # model.forward(dataset.data[:][0])

    # 获取数据集中的特征变量
    X = dataset.dataset[:][0]
    # 获取数据集中的标签
    y = dataset.dataset[:][1]
    # 计算模型在当前数据集上的预测输出标记
    z_hat = model.forward(X)
    sigma = F.softmax(z_hat, dim=1)
    is_correct = torch.argmax(input=sigma, dim=1).flatten() == y.flatten()
    # 计算分类准确度
    accuracy = torch.mean(is_correct.float())
    
    return accuracy

In [21]:
# 在计算机的内存中一次性存储数值0~8, 选择数据结构张量 => 确定张量的维度和各个维度上的形状, 张量的数据类型由元素的数据类型确定
t = torch.arange(start=0, end=9, step=1).reshape(3, 3).float()
t

tensor([[0., 1., 2.],
        [3., 4., 5.],
        [6., 7., 8.]])

In [23]:
F.softmax(t, dim=1)

tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]])

In [24]:
torch.manual_seed(55)

# 加载原始数据集
X, y = tensorGenCla()

# 将原始数据集划分为训练数据集和测试数据集, 同时将分别将训练和测试数据集按照指定的大小划分为若干个互不相交的子集
dataset_train, dataset_test = split_loader(X=X, y=y)

In [25]:
# 搭建深度神经网络模型架构
torch.manual_seed(55)

# 搭建深度神经网络模型的架构
# 搭建模型: 使用面向对象(定义类/创建对象)的方式 继承nn.Module类
class GeoffNet(nn.Module):
    # 构造器 + 类/对象属性
    # => 子类的对象调用父类的构造器
    # => 神经网络模型中的各种层
    def __init__(self, in_features=2, out_features=3, bias=False):
        super(GeoffNet, self).__init__()

        self.output_linear = nn.Linear(in_features=in_features, out_features=out_features)

    # 方法
    # => 前向传播: 数据从神经网络的输入层 -> 隐藏层 -> 输出层; 逐层完成整合信息+加工信息
    def forward(self, X):
        # 输入层 -> 输出层
        # 整合信息
        z_hat = self.output_linear(X)
        # 加工信息
        # sigma = F.softmax(z_hat)
        # return sigma
        return z_hat

# 实例化模型
net = GeoffNet()

In [26]:
torch.manual_seed(55)

# 选择合适的损失函数
criterion = nn.CrossEntropyLoss()

# 选择合适的优化器
eta = 0.03
optimizer = optim.SGD(params=net.parameters(), lr=eta)

In [27]:
torch.manual_seed(55)

# 训练模型
fit(n_epochs=3, batched_dataset=dataset_train, model=net, criterion=criterion, optimizer=optimizer, task="clf")

In [28]:
# 计算完成训练的模型在训练数据集上的模型评价指标-分类准确度
calc_accuracy(dataset=dataset_train, model=net)

tensor(0.8790)

In [29]:
# 计算完成训练的模型在测试数据集上的模型评价指标-分类准确度
calc_accuracy(dataset=dataset_test, model=net)

tensor(0.8622)